### ISSUE TITLE
[GWS - 12] Research: HMR  (Webpack Hot Module Replacement) - The following modules couldn't be hot updated

### ISSUE THREAD

**Issue by wwwebman** [wwwebman/gulp-webpack-starter#14]
HMR process-update.js :
Ignored an update to unaccepted module ...
(Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves.

Current solution:

```js
entry: {
 app: [
  'webpack-hot-middleware/client?reload=true',
  './main.js',
  ]
 }
```

**Comment by markonijum** [comment]
I noticed when saving any .js file browser start infinit reloading loop. 
Solution for me was to change line in browserSync.js file. Problem is with publicPath property in webpackDevMiddleware. 
Just change "publicPath: webpackConfig.output.publicPath" with
publicPath: path.resolve (webpackConfig.output.publicPath).
Of course you should require ('path') module:
const path = require ('path')

**Comment by wwwebman** [comment]
Hello @markonijum ! It would be great if you will send fix via pull request.
