### ISSUE TITLE
[GWS 14]  'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ukozdan** [wwwebman/gulp-webpack-starter#26]
Running on Windows 10: 

```javascript
yarn build
yarn run v1.3.2
$ NODE_ENV=production gulp
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

[Some suggest](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman) it may be a cross platform syntax issue.

**Comment by wwwebman** [comment]
@ukozdan, Hi! Did you find any solution to fix this bug?

**Comment by ukozdan** [comment]
@wwwebman No, the link I included suggested it may be because the line: 
```javascript
$ NODE_ENV=production gulp
```
is Linux, but not Windows friendly. I don't know if changing it to the following would cause more issues: 
```javascript
$ NODE_ENV=production
gulp
```

**Comment by wwwebman** [comment]
@ukozdan fixed:
https://github.com/wwwebman/gulp-webpack-starter/commit/66d3df0d2970faef50d694b30e253ba0ea93da36

**Comment by ukozdan** [comment]
Cool
