### ISSUE TITLE
Why no webpack.config.js?

### ISSUE THREAD

**Issue by ukozdan** [wwwebman/gulp-webpack-starter#28]
I am new to webpack, but every setup has a webpack.config.js. Is there a reason why you have used this file?

**Comment by wwwebman** [comment]
We are use:
https://github.com/wwwebman/gulp-webpack-starter/blob/master/tasks/webpack.config.js

Webpack used only for js bundling.

@ukozdan ask any other questions on chat https://gitter.im/gulp-webpack-starter/Lobby and, please, don't create issue for that. Thanks!

**Comment by ukozdan** [comment]
Apologies; my mistake.
