### ISSUE TITLE
[GWS - 13] Big js bundle file size

### ISSUE THREAD

**Issue by majek88** [wwwebman/gulp-webpack-starter#34]
# Expected Behavior

Smaller size of bundle.js (faster compile)

# Current Behavior

It takes very long to compile js. The bundle.js file is very big.

**Comment by wwwebman** [comment]
Hi @majek88! 
If I imagine correct you situation, you do some changes in *.js files and wait too long until page will be refreshed with you changes? So, it is your propose above how to handle it?

**Comment by wwwebman** [comment]
@majek88 I'll close this issue for clean up. Please reopen if you can discuss further on how we can archive this.
