### ISSUE TITLE
Page in the browser in infinity refresh

### ISSUE THREAD

**Issue by pathliving** [wwwebman/gulp-webpack-starter#35]
# Expected Behavior

Normal project reassembly after edit and compile JS file

# Current Behavior

Page in the browser in infinity refresh

# Failure Information (for bugs)

## Steps to Reproduce

Detailed steps for reproducing the issue.

1. clone repo on locale pc
2. yarn
3. yarn start
4. change any JS file
5. task manager after compile JS file in a loop (page in the browser in infinity refresh)

## Context
* Operating System - windows 10 1803
* Node version - v8.11.3

**Comment by wwwebman** [comment]
Hi @pathliving.
Topic is related to issue #3.
But you don't use proxy, right?. Have you tried to update Node to 8.9.4 (as recommended)? If not, please do! Then if problem will still occur let me know.

**Comment by wwwebman** [comment]
@pathliving because of no response I have to close issue.
