### ISSUE TITLE
Yarn start under Windows  svg sprite problem

### ISSUE THREAD

**Issue by Wyzix33** [wwwebman/gulp-webpack-starter#37]
# Expected Behavior
_sprite.scss should be created inside dev folder:
C:\nodejs\api\dev\sass\parts\vendor\_sprite.scss

# Current Behavior

_sprite.scss is created inside dist/dev folder:
C:\nodejs\api\dist\dev\sass\parts\vendor\_sprite.scss

# Failure Information (for bugs)

when i run 

> yarn start

 i get this error:
```
[12:02:07] gulp-notify: [Error running Gulp] Error: dev\sass\parts\vendor\_icons.scss
Error: File to import not found or unreadable: sprite.
        on line 5 of dev/sass/parts/vendor/_icons.scss
        from line 8 of dev/sass/parts/vendor/_index.scss
        from line 11 of dev/sass/bundle.scss
>> @import 'sprite';

   ^
```

## Steps to Reproduce

1.Download gulp-webpack-starter
2. run in console

```
yarn
yarn start
```

## Context

Windows 10 home
npm version 6.4.1
node version v10.10.0

Thanks

**Comment by wwwebman** [comment]
Should be fixed. Please, check!
