### ISSUE TITLE
Not found bundle.js

### ISSUE THREAD

**Issue by caseydev** [wwwebman/gulp-webpack-starter#39]
I got issue while compiling js. Its working on local but while i have upload to server it won't work

![image](https://user-images.githubusercontent.com/4696688/54470814-b8c4f600-47d6-11e9-9350-b7d136138e3c.png)
there is no js folder inside dist folder 

![image](https://user-images.githubusercontent.com/4696688/54470820-d09c7a00-47d6-11e9-922d-7b7af73d531c.png)
on live server when i try to open bundle.js

**Comment by wwwebman** [comment]
@caseydev  pleas add screen with ./dev/js folder. Would be nice if you can send  info about your OS and npm, node versions. Did you do any packages updates?

**Comment by caseydev** [comment]
@wwwebman 
![image](https://user-images.githubusercontent.com/4696688/54833032-665b6c00-4ce5-11e9-9694-2983efbbdcb9.png)
![image](https://user-images.githubusercontent.com/4696688/54833084-7ffcb380-4ce5-11e9-858f-be5954f0e090.png)

OS: Macos Mojave

**Comment by wwwebman** [comment]
@caseydev Sorry, haven't too much time to check it. Maybe you already have found the reason of that bug?

**Comment by wwwebman** [comment]
I close this issue. Please open one more time in case of issue.
