### ISSUE TITLE
Infinity refresh on the Google Chrome

### ISSUE THREAD

**Issue by Cr3atiwww** [wwwebman/gulp-webpack-starter#55]
# Expected Behavior

This the same case as #35 

# Current Behavior

I don't use WordPress, so I don't use proxy mode. 

## Steps to Reproduce

1. Everything is OK except JS files.
2. The result of each change on the JS files is infinite refreshment on the browser.

## Context

* OS: Windows 10 64bit Version 1909
* Node.js 8.9.4

**Comment by wwwebman** [comment]
1. Do go [ this way](https://github.com/wwwebman/gulp-webpack-starter#dart-1-static-html-templating), right?
2. Please upgrade node.js to version 10.16.0 (starting from #53  it is a minimal one).
3.  If the issue still appears let me know below. I will be grateful for some demo (e.g. on your Github).

**Comment by Cr3atiwww** [comment]
Thanks for the quick answer. I decided to opt out of using Windows for MacOS finally (migration from PC to laptop) :D
