### ISSUE TITLE
Browser-sync streaming

### ISSUE THREAD

**Issue by innomerphey** [wwwebman/gulp-webpack-starter#76]
Thanks for the great  starter!

What is the purpose of streaming everything. Does that really make sense?

`.pipe(reload({ stream: true })));`

Please check the documentation. I think the parameter ` stream: true` is deprecated

**Comment by wwwebman** [comment]
Hi @innomerphey, thanks and:
1. This way we inform BrowserSync about changes. I believe there are many more options. At least the following one does the same trick - https://browsersync.io/docs/api#api-stream.
2. I saw no depreciation. Can you send a link where did you read that?

**Comment by innomerphey** [comment]
https://github.com/BrowserSync/browser-sync/blob/92bf7d84894e9171ed8e313909d473bbd6c7368d/packages/browser-sync/lib/public/reload.js#L19

**Comment by wwwebman** [comment]
1. Well, this still not argues that it was deprecated. But I would agree that our solution should we refactored with `bs.stream()`.
2. I don't know how do you understand how streaming works, but for me, it's the event the BrowserSync listens and reacts to it. As a result, it can **inject or refresh**:

> Browsersync can watch your files as you work. Changes you make will either be injected into the page (CSS & images) or will cause all browsers to do a full-page refresh. 

So to make an **injection**, you might need to use https://www.npmjs.com/package/bs-html-injector.
P.S. I have never tried this, but if you figure out how to integrate to gulp-webpack-starter, welcome to PR.
